version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-new4"
s3_bucket = "mynews4bucket-new"
s3_prefix = "sam-app-new4"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
